branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: chore
          scope: shared-workflows
          release: patch
  - "@semantic-release/github"
