name: Check - Yarn and dependencies
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  duplicate-dependencies:
    name: Check for duplicate dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup yarn tools
        uses: nikobockerman/github-actions/.github/actions/yarn-project-setup@f204e7207f7303c894a97b3ad437855085808476
      - name: Check for duplicate dependencies
        run: yarn dedupe --check

  yarn-install-errors:
    name: Validate Yarn install does not contain errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup project
        uses: nikobockerman/github-actions/.github/actions/yarn-project-setup@f204e7207f7303c894a97b3ad437855085808476
      - name: Yarn install output check
        run: |
          errors=$(yarn install --json | jq 'select(.displayName != "YN0000")')
          error_count=$(echo "$errors" | jq -s 'length')
          if [ "$error_count" -gt 0 ]; then
            echo "Detected Yarn install errors: $error_count"
            echo -e "$errors"
            exit 1
          fi

  peer-requirements:
    name: Validate yarn peer requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup project
        uses: nikobockerman/github-actions/.github/actions/yarn-project-setup@f204e7207f7303c894a97b3ad437855085808476
      - name: Validate peer requirements are defined
        run: |
          reqs=$(yarn explain peer-requirements)
          echo "$reqs" | grep '✘' || true
          echo "$reqs" | grep -q '✘' && exit 1 || exit 0
