name: Check - prettier
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  prettier:
    name: Check formatting with prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup yarn tools
        uses: nikobockerman/github-actions/.github/actions/yarn-project-setup@1a98f54edb21bf5f2de5446215c638debc271cac
      - name: Check prettier
        run: yarn run -B prettier --check .
