name: Check - GitHub actions
on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "package.json"
      - "yarn.lock"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  actions:
    name: Check GitHub actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup tools
        uses: nikobockerman/github-actions/.github/actions/yarn-project-setup@4669ec8b8f7b3e120b630dd43880346bf518179b
      - name: Check GitHub actions
        run: git ls-files '.github/**.yaml' | xargs -t -I {} yarn run -B action-validator {}
