name: Check - Renovate config
on:
  pull_request:
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/check-renovate-config.yaml"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  renovate-config-validator:
    name: Renovate config validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Renovate config validator
        run: npx --package=renovate@latest --yes --prefer-online renovate-config-validator --strict
