name: Check - GitHub actions
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  actions:
    name: Check GitHub actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup tools
        uses: nikobockerman/github-actions/.github/actions/yarn-project-setup@4b18697140500333979b12fc41ff0cd2409f39fe
      - name: Check GitHub actions
        run: git ls-files '.github/**.yaml' | xargs -t -I {} yarn run -B action-validator {}
