name: Check - prettier
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  prettier:
    name: Check formatting with prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup yarn tools
        uses: nikobockerman/github-actions/.github/actions/yarn-project-setup@e016a979d6e455bb4023977985040870b466cace
      - name: Check prettier
        run: yarn run -B prettier --check .
