name: Check - Devcontainer
on:
  workflow_call:
    inputs:
      runCmd:
        default: /bin/sleep 1
        description: Command to run
        required: false
        type: string
permissions:
  contents: read

jobs:
  check:
    name: Check Devcontainer works
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check Devcontainer
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          cacheFrom: |
            type=registry,ref=ghcr.io/${{ github.repository }}-devcontainer:cache
            type=registry,ref=ghcr.io/${{ github.repository }}-devcontainer:cache-intermediate
          push: never
          runCmd: ${{ inputs.runCmd }}
