name: Check - Enforce all checks pass
on:
  pull_request:
  workflow_call:

jobs:
  enforce-all-checks:
    name: Enforce all checks pass
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@899c768d191b56eef585c18f8558da19e1f3e707 # v0.6.0
        with:
          # Ignore and ignore_pattern need to contain name of the job and it
          # isn't available in any context.
          ignore: "Enforce all checks pass"
          ignore_pattern: ".*\\/ Enforce all checks pass$"
          token: ${{ secrets.GITHUB_TOKEN }}
