name: CI
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  mise-cache:
    uses: ./.github/workflows/mise-prepare-cache.yaml
  check-prettier:
    needs: mise-cache
    uses: ./.github/workflows/mise-task.yaml
    with:
      task: check:prettier
  check-renovate-config:
    needs: mise-cache
    uses: ./.github/workflows/mise-task.yaml
    with:
      task: check:renovateconfig

  check:
    needs:
      - check-prettier
      - check-renovate-config
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
