name: Devcontainer image cache
on:
  workflow_call:
    inputs:
      cache-type:
        description: "Cache type: 'intermediate' or 'final'"
        required: true
        type: string
permissions:
  contents: read
  packages: write

jobs:
  args:
    name: Prepare arguments
    runs-on: ubuntu-latest
    outputs:
      cacheFromArg: ${{ steps.args.outputs.cacheFrom }}
      cacheToArg: ${{ steps.args.outputs.cacheTo }}
      registry: ${{ steps.args.outputs.registry }}
    steps:
      - name: Process input arguments
        id: args
        env:
          CACHE_TYPE: ${{ inputs.cache-type }}
          REPOSITORY: ${{ github.repository }}
        run: |
          registry=ghcr.io
          imageRef=${registry}/${REPOSITORY}-devcontainer
          echo "registry=${registry}" >> $GITHUB_OUTPUT
          if [ "${CACHE_TYPE}" == "intermediate" ]; then
            echo "cacheFrom=type=registry,ref=${imageRef}:cache" >> $GITHUB_OUTPUT
            echo "cacheTo=type=registry,ref=${imageRef}:cache-intermediate" >> $GITHUB_OUTPUT
          elif [ "${CACHE_TYPE}" == "final" ]; then
            echo "cacheFrom=type=registry,ref=${imageRef}:cache-intermediate" >> $GITHUB_OUTPUT
            echo "cacheTo=type=registry,ref=${imageRef}:cache" >> $GITHUB_OUTPUT
          else
            echo "Invalid mode: ${CACHE_TYPE}"
            exit 1
          fi
  deploy:
    name: Deploy Devcontainer cache
    needs: args
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ needs.args.outputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build devcontainer and cache to registry
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          cacheFrom: ${{ needs.args.outputs.cacheFromArg }}
          cacheTo: ${{ needs.args.outputs.cacheToArg }}
          push: never
