name: Mise task
on:
  workflow_call:
    inputs:
      task:
        description: Task to run
        required: true
        type: string
      runner:
        description: runner to use
        required: false
        type: string
        default: ubuntu-latest
permissions:
  contents: read

jobs:
  task:
    name: Run mise task - ${{ inputs.task }}
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup mise
        uses: nikobockerman/github-actions/.github/actions/mise-project-setup@254a14880f8b900c2caee7bccf098fc1208ff46e # v1.0.22
      - name: Run task - ${{ inputs.task }}
        run: mise run ${{ inputs.task }}
        shell: bash
