name: Mise - prepare cache
on:
  workflow_call:
    inputs:
      runner:
        description: runner to use
        required: false
        type: string
        default: ubuntu-latest
permissions:
  contents: read

jobs:
  prepare-cache:
    name: Prepare Mise cache
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          sparse-checkout: |
            mise.toml
      - name: Prepare cache
        uses: nikobockerman/github-actions/.github/actions/mise-project-setup@d2cedde68b0ee836c0e6fc12c818068a2d502f75 # v1.0.17
        with:
          cache-mode: "prepare"
