name: Mise task
on:
  workflow_call:
    inputs:
      task:
        description: Task to run
        required: true
        type: string
      runner:
        description: runner to use
        required: false
        type: string
        default: ubuntu-latest
permissions:
  contents: read

jobs:
  task:
    name: Run mise task - ${{ inputs.task }}
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup mise
        uses: nikobockerman/github-actions/.github/actions/mise-project-setup@3de1c928d4a536a79af361d7d8d0c6e573160b04 # v1.0.13
      - name: Run task - ${{ inputs.task }}
        run: mise run ${{ inputs.task }}
        shell: bash
