name: Mise task
on:
  workflow_call:
    inputs:
      task:
        description: Task to run
        required: true
        type: string
      runner:
        description: runner to use
        required: false
        type: string
        default: ubuntu-latest
permissions:
  contents: read

jobs:
  task:
    name: Run mise task - ${{ inputs.task }}
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run task - ${{ inputs.task }}
        uses: nikobockerman/github-actions/.github/actions/mise-project-task@8e2192ea1f13275dc40372b4581ebe09175d04a1
        with:
          task: ${{ inputs.task }}
