name: Mise - prepare cache
on:
  workflow_call:
    inputs:
      runner:
        description: runner to use
        required: false
        type: string
        default: ubuntu-latest
permissions:
  contents: read

jobs:
  prepare-cache:
    name: Prepare Mise cache
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Prepare cache
        uses: nikobockerman/github-actions/.github/actions/mise-project-setup@e016a979d6e455bb4023977985040870b466cace
        with:
          cache_save: true
