name: Mise - prepare cache
on:
  workflow_call:
    inputs:
      runner:
        description: runner to use
        required: false
        type: string
        default: ubuntu-latest
permissions:
  contents: read

jobs:
  prepare-cache:
    name: Prepare Mise cache
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            mise.toml
      - name: Prepare cache
        uses: nikobockerman/github-actions/.github/actions/mise-project-setup@f6cdf8305a91df367fe5ff8e37b6ac40af40fd4f
        with:
          cache-mode: "prepare"
